### PR TITLE
NAS-114929 / 22.02.1 / add py-nvme to build

### PR DESCRIPTION
**Pull request by yocalebo**
This module adds support persistent reservations for nvme devices.

### CODE REVIEW

**Review by william-gr — COMMENTED** [review]
Building failing, does it need to be added as a dependency of middlewared?

**Comment by sonicaj** [comment]
It should probably be a dependency of `py-fenced`

**Comment by yocalebo** [comment]
retest this please

**Comment by yocalebo** [comment]
Yeah, not sure. python3-nvme is a predepend for python3-fenced and those are building without issues. Not sure why middlewared is failing.

**Comment by sonicaj** [comment]
It should be added as a `Depends` for `python3-fenced` as well

**Comment by yocalebo** [comment]
> It should be added as a `Depends` for `python3-fenced` as well

I've only ever listed `python3-sgio` as a pre-depend for `python3-fenced` so why would this be different?

**Comment by sonicaj** [comment]
@yocalebo because it's already added as `Depends` in middlewared control file. Also idk why you are using `Pre-Depends` :) ( https://www.debian.org/doc/debian-policy/ch-relationships.html )
```
Pre-Depends should be used sparingly, preferably only by packages whose premature upgrade or installation would hamper the ability of the system to continue with any upgrade that might be in progress.
```

**Comment by yocalebo** [comment]
> @yocalebo because it's already added as `Depends` in middlewared control file. Also idk why you are using `Pre-Depends` :) ( https://www.debian.org/doc/debian-policy/ch-relationships.html )
> 
> ```
> Pre-Depends should be used sparingly, preferably only by packages whose premature upgrade or installation would hamper the ability of the system to continue with any upgrade that might be in progress.
> ```

Because that's how it has always been 😄 Why change something when it has been working? I added `python3-nvme` as a build depend here: https://github.com/truenas/middleware/pull/8319

**Comment by sonicaj** [comment]
We should correctly specify the dependency right now then ;)

**Comment by yocalebo** [comment]
retest this please

**Comment by yocalebo** [comment]
@sonicaj ping since the surrounding issues have been fixed.

**Review by sonicaj — APPROVED** [review]

**Pull request merged**
