### PR TITLE
NAS-113276 / 22.02-RC.2 / Adapt to using debian EFI image

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Comment by themylogin** [comment]
time 15:00

**Comment by themylogin** [comment]
retest this please

**Comment by themylogin** [comment]
retest this please

**Comment by themylogin** [comment]
retest this please

**Comment by themylogin** [comment]
retest this please

**Comment by themylogin** [comment]
time 5:30

**Review by sonicaj — APPROVED** [review]

**Pull request merged**
