### PR TITLE
NAS-115331 / 22.12 / Build scale with 5.15 kernel

### PR DESCRIPTION
**Pull request by sonicaj**

### CODE REVIEW

**Comment by sonicaj** [comment]
retest this please

**Comment by sonicaj** [comment]
Will update kernel branch once OS team has finalized stable branch for 5.15

**Review by william-gr — APPROVED** [review]

**Comment by sonicaj** [comment]
retest this please

**Comment by ErroneousBosch** [comment]
Is there a chance of this being backported, since it in theory brings Alder Lake iGPU support?

**Pull request merged**
