### PR TITLE
NAS-132596 / 25.04 / Move nvidia extension to the rootfs image

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Comment by themylogin** [comment]
http://jenkins.eng.ixsystems.net:8080/job/master/job/custom/742/

**Comment by themylogin** [comment]
@yocalebo works on rebuilder, trying on Jenkins. Ready for review I guess.

**Comment by themylogin** [comment]
time 18:00

**Comment by themylogin** [comment]
https://github.com/truenas/scale-build/pull/756
https://github.com/truenas/scale-build/pull/758
need to be backported first

**Review by yocalebo — APPROVED** [review]

**Pull request merged**
