### PR TITLE
[NAS-118248] Add sysfsutils package

### PR DESCRIPTION
**Pull request by SuperQ**
Add the `sysfsutils` package to the build manifest. This allows simple tweaks of file attributes in the `/sys` filesystem.

Signed-off-by: SuperQ <superq@gmail.com>

### CODE REVIEW

**Comment by freqlabs** [comment]
I'm not convinced this is that useful. It's already pretty simple to manipulate files in sysfs.

**Comment by SuperQ** [comment]
It's simple, but this package makes it easy to make it persistent across reboots. That's the "hard" part that this helps solve.

**Comment by yocalebo** [comment]
It also allows them to be persistent across reboots and upgrades.

**Comment by SuperQ** [comment]
@yocalebo Nice. Will that also allow for sysfs filesystem permission/ownership changes?

**Comment by SuperQ** [comment]
Note, my plan was to also add API support to control the tuning features that this package allows for. This was just to get the idea rolling and provide the framework (`/etc/sysfs.d/*.conf`) to do those configurations.

**Comment by SuperQ** [comment]
My use case is to adjust the permissions/group (for group read) of `/sys/class/powercap/intel-rapl:*/energy_uj` to allow monitoring software to collect metrics as non-root. Otherwise the monitoring agent needs root, which I like to avoid.

**Comment by freqlabs** [comment]
> It's simple, but this package makes it easy to make it persistent across reboots. That's the "hard" part that this helps solve.

This can be done easily enough with [tmpfiles.d](https://www.freedesktop.org/software/systemd/man/tmpfiles.d.html) already. I find it best to avoid relying on additional dependencies especially during system startup.

**Comment by SuperQ** [comment]
Oh, that's an interesting option. I'll check it out to see if it works for this.

**Comment by yocalebo** [comment]
As discussed earlier, I've got a branch that I haven't pushed that adds the ability to change sysfs settings via our API so there is no need for adding this at this time. I'll consider adding the "perms" portion as I work on it more.

**Comment by SuperQ** [comment]
That sound great, thanks!

**Pull request closed without merging**
