### PR TITLE
NAS-106154 / 21.06 / Add openseachest to build

### PR DESCRIPTION
**Pull request by sonicaj**

### CODE REVIEW

**Comment by yocalebo** [comment]
I'm assuming the benefit to having this utility is specifically for flashing firmware for seagate drives? Or in other words, what does this offer for us that we don't already get via sg3_utils and/or nvme-cli?

**Comment by rick-mesta** [comment]
So, at the risk of arriving at the party a bit late, I'm concerned that we're continuing to bloat an already sluggish build process. To @yocalebo's point, what is the value-add of having OpenSeaChest, when (AFAIK) we don't ship Seagate drives on iX branded hardware ? @pkgdemon: any strong opinion here ?

**Comment by sonicaj** [comment]
@darkfiberiru can you please clarify usage ?

**Comment by darkfiberiru** [comment]
Sorry I thought I only had a direct question in slack and missed this.
We actually use it as standard tool for flashing almost any drives firmware. While written by seagate primarily it will work with any drive that works with open standards. It allows almost any type of drive management and very often in a much more friendly and useful way then mentioned tools. This is of high importance to me.



From ReadME on there github

> (Note: The openSeaChest team has the utmost respect for the highly regarded sg3_utils, hdparm, sdparm and nvme-cli open source projects. Since this is all pretty low-level stuff, we chose the presentation title "What's better than sg3_utils, hdparm, sdparm?" only to grab the attention of a few extra people attending the SNIA SDC 2018 conference.)
https://www.youtube.com/watch?v=LMt8Ztlj5oQ

**Comment by sonicaj** [comment]
@pkgdemon @rick-mesta the debian package has already been made, we just need to add it to build now ; )

**Comment by rick-mesta** [comment]
I've shut my pie-hole, now... if you guys need it, then that's that

**Review by yocalebo — APPROVED** [review]

**Pull request merged**
