### PR TITLE
NAS-132923 / 25.04 / Build `dev-tools` extension

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Comment by themylogin** [comment]
http://jenkins.eng.ixsystems.net:8080/job/master/job/custom/809/

**Review by sonicaj — APPROVED** [review]

**Review by sonicaj — COMMENTED** [review]
Can we please update README to reflect new RAM requirement ?

**Comment by themylogin** [comment]
@sonicaj done

**Comment by themylogin** [comment]
time 24:00

**Pull request merged**
