### PR TITLE
NAS-113898 / 22.12 / Add PowerTop to SCALE

### PR DESCRIPTION
**Pull request by Ornias1993**
Powertop is a vital Intel-provided tool for monitoring per-process powerconsumption on power-efficiency focussed systems.
It also allows access to some intel-adviced optimalisations, which is, ofcoarse, not actively supported.

Ofcoarse it does not enable any running-by-default services and also does not make any system changes by default either. Unless manually enabled by the user to do so.

It has to be noted that users of more power-optimised NAS systems are one of the side audiences that SCALE appeals to (as the linux kernel is generally more power efficient), adding this also caters to said audience.

**Testing**
I've manually installed powertop and verified it to be working.
As a precautionary test I also tried to auto-optimise feature on a fujitsu/kontron motherboard with intel i7-9700, to ensure it does not inherently cause damage and/or stability issues to the system. No issues where noticed.

### CODE REVIEW

**Comment by Ornias1993** [comment]
> Can one of the admins verify this patch?

Either this bot is fake and this PR just got ignored on purpose or broken and needs to be verified itself.

**Comment by kmoore134** [comment]
ok to test

**Review by sonicaj — APPROVED** [review]

**Comment by sonicaj** [comment]
Thanks @Ornias1993!

**Comment by Ornias1993** [comment]
Might also be nice to backport to next 22.02 minor release, considering apt is disabled now.

**Comment by sonicaj** [comment]
backport

**Pull request merged**
